#!/command/with-contenv bash
# shellcheck shell=bash

set -e

echo
echo
cat /etc/s6-overlay/s6-rc.d/init-adduser/branding
echo
echo

NEW_UID=1000
NEW_GID=1000
if [[ ! -z "$PGID" ]]; then
    NEW_GID=$PGID
fi
if [[ ! -z "$PUID" ]]; then
    NEW_UID=$PUID
fi

if ! getent group _mandos >/dev/null 2>&1; then
    echo "[adduser] Adding group _mandos with $NEW_GID"
    groupadd --gid $NEW_GID _mandos
fi

if ! getent passwd _mandos >/dev/null 2>&1; then
    echo "[adduser] Adding user _mandos with $NEW_UID"
    useradd --uid $NEW_UID --gid $NEW_GID --shell /bin/false --no-user-group --no-create-home _mandos
fi