#!/command/with-contenv bash
# shellcheck shell=bash

echo "[svc-mandos2matrix] Starting service"
exec s6-setuidgid _mandos /usr/bin/mandos2matrix --initial-config /mandos2matrix/initial.json --runtime-config /mandos2matrix/runtime.json
