#!/command/with-contenv bash
# shellcheck shell=bash

echo "[svc-mandos] Starting service with log level $LOGLEVEL"
exec s6-setuidgid _mandos /usr/sbin/mandos --foreground --no-zeroconf -p 8080 --configdir /etc/mandos --statedir /var/lib/mandos --debuglevel $LOGLEVEL
